pub mod buffers;
pub mod camera;
pub mod commands;
pub mod compute_cull;
pub mod depth;
pub mod descriptors;
pub mod frustum;
pub mod gpu;
pub mod input;
pub mod instance;
pub mod memory;
pub mod mesh;
pub mod mesh_pool;
pub mod palette_buffer;
pub mod pipeline;
pub mod queue_families;
pub mod render_pass;
pub mod scene;
mod shaders;
pub mod swapchain;
pub mod texture_mapping;
pub mod vulkan_object;

const MAX_FRAMES_IN_FLIGHT: usize = 2;
